// <auto-generated />
using Evolve_Game.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evolve_Game.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241212145412_PlayerEquipId")]
    partial class PlayerEquipId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Evolve_Game.Entities.AtributteElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AtributteElements");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Chest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DropId")
                        .HasColumnType("int");

                    b.Property<int>("IdDrop")
                        .HasColumnType("int");

                    b.Property<int>("IdIcon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DropId");

                    b.ToTable("Chests");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Drop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drops");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DropEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChanceDrop")
                        .HasColumnType("real");

                    b.Property<int>("IdDrop")
                        .HasColumnType("int");

                    b.Property<int>("IdEquip")
                        .HasColumnType("int");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDrop");

                    b.HasIndex("IdEquip");

                    b.ToTable("DropEquips");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DropItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChanceDrop")
                        .HasColumnType("real");

                    b.Property<int>("IdDrop")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDrop");

                    b.HasIndex("IdItem");

                    b.ToTable("DropItems");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosMax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DungeonChest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChanceApper")
                        .HasColumnType("real");

                    b.Property<int?>("DungeonId")
                        .HasColumnType("int");

                    b.Property<int>("IdChest")
                        .HasColumnType("int");

                    b.Property<int>("IdDungeon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.HasIndex("IdChest");

                    b.HasIndex("IdDungeon");

                    b.ToTable("DungeonChests");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DungeonMonster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DungeonId")
                        .HasColumnType("int");

                    b.Property<int>("IdDungeon")
                        .HasColumnType("int");

                    b.Property<int>("IdMonster")
                        .HasColumnType("int");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.HasIndex("IdDungeon");

                    b.HasIndex("IdMonster");

                    b.ToTable("DungeonMonsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Effect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectActive")
                        .HasColumnType("int");

                    b.Property<int?>("EffectsConectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEffectAttackContinue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEffectContinue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEffectDamageContinue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEffectPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EffectsConectionId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EffectList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEffect")
                        .HasColumnType("int");

                    b.Property<int>("IdEffectsConection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEffect");

                    b.HasIndex("IdEffectsConection");

                    b.ToTable("EffectList");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EffectsConection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EffectsConections");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Equip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CriticalChanceMax")
                        .HasColumnType("real");

                    b.Property<float>("CriticalChanceMin")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamageMax")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamageMin")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("IdEffectsConection")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipType")
                        .HasColumnType("int");

                    b.Property<int>("IdIcon")
                        .HasColumnType("int");

                    b.Property<int>("IdRarity")
                        .HasColumnType("int");

                    b.Property<int>("LifeMax")
                        .HasColumnType("int");

                    b.Property<int>("LifeMin")
                        .HasColumnType("int");

                    b.Property<int>("MagicDamageMax")
                        .HasColumnType("int");

                    b.Property<int>("MagicDamageMin")
                        .HasColumnType("int");

                    b.Property<int>("MagicDefenseMax")
                        .HasColumnType("int");

                    b.Property<int>("MagicDefenseMin")
                        .HasColumnType("int");

                    b.Property<int>("MagicolaMax")
                        .HasColumnType("int");

                    b.Property<int>("MagicolaMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalDamageMax")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDamageMin")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDefenseMax")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDefenseMin")
                        .HasColumnType("int");

                    b.Property<float>("SpeedAttackMax")
                        .HasColumnType("real");

                    b.Property<float>("SpeedAttackMin")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdEffectsConection");

                    b.HasIndex("IdEquipType");

                    b.HasIndex("IdRarity");

                    b.ToTable("Equips");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EquipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipTypes");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EvolutionMonster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdMonsterEvolution")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMonster");

                    b.HasIndex("IdMonsterEvolution");

                    b.ToTable("EvolutionMonsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EvolutionTerms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdEvolutionMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdEvolutionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEvolutionMonster");

                    b.HasIndex("IdEvolutionType");

                    b.ToTable("EvolutionTerms");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EvolutionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvolutionTypes");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Icon")
                        .HasColumnType("int");

                    b.Property<int>("IdEffectsConection")
                        .HasColumnType("int");

                    b.Property<int>("IdRarity")
                        .HasColumnType("int");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEffectsConection");

                    b.HasIndex("IdRarity");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CriticalChance")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamage")
                        .HasColumnType("real");

                    b.Property<float>("DefenseFairy")
                        .HasColumnType("real");

                    b.Property<float>("DefenseFire")
                        .HasColumnType("real");

                    b.Property<float>("DefenseLight")
                        .HasColumnType("real");

                    b.Property<float>("DefenseShadow")
                        .HasColumnType("real");

                    b.Property<float>("DefenseWater")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoldKill")
                        .HasColumnType("int");

                    b.Property<int>("IdDrop")
                        .HasColumnType("int");

                    b.Property<int>("IdEffectsConection")
                        .HasColumnType("int");

                    b.Property<int>("IdRarity")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecie")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<int>("MagicDamage")
                        .HasColumnType("int");

                    b.Property<int>("MagicDefense")
                        .HasColumnType("int");

                    b.Property<int>("Magicola")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDefense")
                        .HasColumnType("int");

                    b.Property<bool>("PosRotation")
                        .HasColumnType("bit");

                    b.Property<float>("ScaleSize")
                        .HasColumnType("real");

                    b.Property<int>("Skin")
                        .HasColumnType("int");

                    b.Property<float>("SpecialFairy")
                        .HasColumnType("real");

                    b.Property<float>("SpecialFire")
                        .HasColumnType("real");

                    b.Property<float>("SpecialLight")
                        .HasColumnType("real");

                    b.Property<float>("SpecialShadow")
                        .HasColumnType("real");

                    b.Property<float>("SpecialWater")
                        .HasColumnType("real");

                    b.Property<float>("SpeedAttack")
                        .HasColumnType("real");

                    b.Property<int>("XpKill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDrop");

                    b.HasIndex("IdEffectsConection");

                    b.HasIndex("IdRarity");

                    b.HasIndex("IdSpecie");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.MonsterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMonster");

                    b.HasIndex("IdSkill");

                    b.ToTable("MonsterSkills");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CriticalChance")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamage")
                        .HasColumnType("real");

                    b.Property<int>("IdEquip")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<int>("MagicDamage")
                        .HasColumnType("int");

                    b.Property<int>("MagicDefense")
                        .HasColumnType("int");

                    b.Property<int>("Magicula")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalDefense")
                        .HasColumnType("int");

                    b.Property<float>("SpeedAttack")
                        .HasColumnType("real");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEquip");

                    b.HasIndex("IdUser");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerEquips");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerEvolutionMonster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEvolutionMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayerMonster")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEvolutionMonster");

                    b.HasIndex("IdPlayerMonster");

                    b.ToTable("PlayerEvolutionMonsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdUser");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorMagicBlack")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicBlue")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicGreen")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicPink")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicPurple")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicRed")
                        .HasColumnType("int");

                    b.Property<int>("ColorMagicWhite")
                        .HasColumnType("int");

                    b.Property<int>("IdMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdRarity")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMonster");

                    b.HasIndex("IdRarity");

                    b.HasIndex("IdUser");

                    b.ToTable("PlayerMonsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonsterEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPlayerEquip")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayerMonster")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayerEquip");

                    b.HasIndex("IdPlayerMonster");

                    b.ToTable("PlayerMonsterEquips");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonsterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPlayerMonster")
                        .HasColumnType("int");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayerMonster");

                    b.HasIndex("IdSkill");

                    b.ToTable("PlayerMonsterSkills");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAtributteElement")
                        .HasColumnType("int");

                    b.Property<int>("IdEffectsConection")
                        .HasColumnType("int");

                    b.Property<int>("IdIcon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAtributteElement");

                    b.HasIndex("IdEffectsConection");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Evolve_Game.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("IdDungeon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosX")
                        .HasColumnType("int");

                    b.Property<int>("PosY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDungeon");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Chest", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Drop", "Drop")
                        .WithMany()
                        .HasForeignKey("DropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drop");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DropEquip", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Drop", "Drop")
                        .WithMany()
                        .HasForeignKey("IdDrop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Equip", "Equip")
                        .WithMany()
                        .HasForeignKey("IdEquip")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drop");

                    b.Navigation("Equip");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DropItem", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Drop", "Drop")
                        .WithMany()
                        .HasForeignKey("IdDrop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drop");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DungeonChest", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Dungeon", null)
                        .WithMany("dungeonChest")
                        .HasForeignKey("DungeonId");

                    b.HasOne("Evolve_Game.Entities.Chest", "Chest")
                        .WithMany()
                        .HasForeignKey("IdChest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Dungeon", "Dungeon")
                        .WithMany()
                        .HasForeignKey("IdDungeon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chest");

                    b.Navigation("Dungeon");
                });

            modelBuilder.Entity("Evolve_Game.Entities.DungeonMonster", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Dungeon", null)
                        .WithMany("dungeonMonsters")
                        .HasForeignKey("DungeonId");

                    b.HasOne("Evolve_Game.Entities.Dungeon", "Dungeon")
                        .WithMany()
                        .HasForeignKey("IdDungeon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("IdMonster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dungeon");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Effect", b =>
                {
                    b.HasOne("Evolve_Game.Entities.EffectsConection", null)
                        .WithMany("Effects")
                        .HasForeignKey("EffectsConectionId");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EffectList", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Effect", "Effect")
                        .WithMany()
                        .HasForeignKey("IdEffect")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.EffectsConection", "EffectsConection")
                        .WithMany()
                        .HasForeignKey("IdEffectsConection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("EffectsConection");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Equip", b =>
                {
                    b.HasOne("Evolve_Game.Entities.EffectsConection", "EffectsConection")
                        .WithMany()
                        .HasForeignKey("IdEffectsConection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.EquipType", "EquipType")
                        .WithMany()
                        .HasForeignKey("IdEquipType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("IdRarity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EffectsConection");

                    b.Navigation("EquipType");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EvolutionMonster", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("IdMonster")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Monster", "MonsterEvolution")
                        .WithMany()
                        .HasForeignKey("IdMonsterEvolution")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("MonsterEvolution");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EvolutionTerms", b =>
                {
                    b.HasOne("Evolve_Game.Entities.EvolutionMonster", "EvolutionMonster")
                        .WithMany()
                        .HasForeignKey("IdEvolutionMonster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.EvolutionType", "EvolutionType")
                        .WithMany()
                        .HasForeignKey("IdEvolutionType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvolutionMonster");

                    b.Navigation("EvolutionType");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Item", b =>
                {
                    b.HasOne("Evolve_Game.Entities.EffectsConection", "EffectsConection")
                        .WithMany()
                        .HasForeignKey("IdEffectsConection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("IdRarity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EffectsConection");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Monster", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Drop", "Drop")
                        .WithMany()
                        .HasForeignKey("IdDrop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.EffectsConection", "EffectsConection")
                        .WithMany()
                        .HasForeignKey("IdEffectsConection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("IdRarity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Specie", "Specie")
                        .WithMany()
                        .HasForeignKey("IdSpecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drop");

                    b.Navigation("EffectsConection");

                    b.Navigation("Rarity");

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Evolve_Game.Entities.MonsterSkill", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("IdMonster")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerEquip", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Equip", "Equip")
                        .WithMany()
                        .HasForeignKey("IdEquip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.User", null)
                        .WithMany("PlayerEquips")
                        .HasForeignKey("UserId");

                    b.Navigation("Equip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerEvolutionMonster", b =>
                {
                    b.HasOne("Evolve_Game.Entities.EvolutionMonster", "EvolutionMonster")
                        .WithMany()
                        .HasForeignKey("IdEvolutionMonster")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.PlayerMonster", "PlayerMonster")
                        .WithMany()
                        .HasForeignKey("IdPlayerMonster")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvolutionMonster");

                    b.Navigation("PlayerMonster");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerItem", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.User", "User")
                        .WithMany("PlayerItems")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonster", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("IdMonster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("IdRarity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.User", "User")
                        .WithMany("PlayerMonsters")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Rarity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonsterEquip", b =>
                {
                    b.HasOne("Evolve_Game.Entities.PlayerEquip", "PlayerEquip")
                        .WithMany()
                        .HasForeignKey("IdPlayerEquip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.PlayerMonster", "PlayerMonster")
                        .WithMany()
                        .HasForeignKey("IdPlayerMonster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEquip");

                    b.Navigation("PlayerMonster");
                });

            modelBuilder.Entity("Evolve_Game.Entities.PlayerMonsterSkill", b =>
                {
                    b.HasOne("Evolve_Game.Entities.PlayerMonster", "PlayerMonster")
                        .WithMany()
                        .HasForeignKey("IdPlayerMonster")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerMonster");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Skill", b =>
                {
                    b.HasOne("Evolve_Game.Entities.AtributteElement", "AtributteElement")
                        .WithMany()
                        .HasForeignKey("IdAtributteElement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evolve_Game.Entities.EffectsConection", "EffectsConection")
                        .WithMany()
                        .HasForeignKey("IdEffectsConection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtributteElement");

                    b.Navigation("EffectsConection");
                });

            modelBuilder.Entity("Evolve_Game.Entities.User", b =>
                {
                    b.HasOne("Evolve_Game.Entities.Dungeon", "Dungeon")
                        .WithMany()
                        .HasForeignKey("IdDungeon")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Dungeon");
                });

            modelBuilder.Entity("Evolve_Game.Entities.Dungeon", b =>
                {
                    b.Navigation("dungeonChest");

                    b.Navigation("dungeonMonsters");
                });

            modelBuilder.Entity("Evolve_Game.Entities.EffectsConection", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Evolve_Game.Entities.User", b =>
                {
                    b.Navigation("PlayerEquips");

                    b.Navigation("PlayerItems");

                    b.Navigation("PlayerMonsters");
                });
#pragma warning restore 612, 618
        }
    }
}
